docs: add new kubernetes build driver docs
docker/buildx pull request #1208
Opened 2022-07-12 15:14 UTC by jedevc

This PR introduces a new kubernetes builder guide to match the remote builder guide previously added in #1093.

The content consolidates some of the information already present in the command line reference, and discussions like https://github.com/docker/buildx/discussions/685.

I think this should be a good first pass of the guide, we might want to follow-up and add some more complex deployment scenarios, though I'm not as familiar with those, so will likely leave them to someone with some more experience there :smile:

2022-07-12 15:24 UTC, AkihiroSuda commented on docs/guides/kubernetes-builder.md
> +To connect buildx to your cluster, you'll first need to create a dedicated
```suggestion
Before setting up buildx for your cluster, you may want to create a dedicated
```

2022-07-12 15:26 UTC, AkihiroSuda commented on docs/guides/kubernetes-builder.md
> +also supports using [QEMU](https://www.qemu.org/) to build non-native platforms.
```suggestion
also supports using [QEMU](https://www.qemu.org/) (user mode) to build non-native platforms.
```

2022-07-13 09:49 UTC, AkihiroSuda approved these changes

2022-07-13 20:22 UTC, crazy-max commented on docs/guides/kubernetes-builder.md
> +With out `kube` driver created, we can now introduce another architecture into
```suggestion
With our `kube` driver created, we can now introduce another architecture into
```

2022-07-13 20:23 UTC, crazy-max requested changes
small typo, otherwise lgtm

2022-07-18 09:17 UTC, crazy-max approved these changes
LGTM

2022-07-19 16:21 UTC, merged