build: assume '.' if no args are passed
docker/buildx pull request #1937
Opened 2023-07-12 16:21 UTC by imjasonh

Before:

```shell
$ docker build -t foo
ERROR: "docker buildx build" requires exactly 1 argument.
# swearing omitted
$ docker build -t foo .
[+] Building 0.4s (3/3) FINISHED
 => [internal] load .dockerignore                                                                                                                                                                            
  ...etc...
```

After:

```shell
$ docker build -t foo
[+] Building 0.4s (3/3) FINISHED
 => [internal] load .dockerignore                                                                                                                                                                            
  ...etc...
```

If this seems fine to you I can make a [similar change in docker/cli](https://github.com/docker/cli/compare/master...imjasonh:cli-1:assume-dot)

2023-07-12 16:27 UTC, thaJeztah requested changes
I need to find related tickets about this (as there was prior discussion with more details), but I don't think we should do this as we're considering keeping this option open for future features (interactive builds). Setting this default means that this will no longer be an option in future.

2023-07-12 21:47 UTC, imjasonh commented
> I need to find related tickets about this (as there was prior discussion with more details), but I don't think we should do this as we're considering keeping this option open for future features (interactive builds). Setting this default means that this will no longer be an option in future.

I totally understand, and that's absolutely your call to make. This CLI is invoked probably bajillions of times each day, and I was pretty sure I wasn't the first person to think of this 😆. Any previous conversation/context about it you could share would be helpful.

Speaking only for myself, I stumble on this embarrassingly often, and I have since I started using Docker years ago (embarrassing, as I said). I imagine others stumble on it too, some small percentage of those bajillions of times per day. It adds up.

I don't know what you plan to do for interactive builds (it sounds cool!) but personally I'd probably get more value out of `docker build -t foo` doing what I've expected it to do for years, rather than start dropping me into some new interactive build experience, just because I forgot the `.` again.

2023-08-01 08:58 UTC, tonistiigi commented
My personal preference would be that no-args could use the current Git state as main context, as this is a much better default because all the sources are immutable and properly tracked.

I don't think this is a quick merge, but we can definitely have an open issue about what the default behavior could be and feedback for various options.

2023-10-19 16:51 UTC, tonistiigi commented
Closing this for now, but we can continue tracking this in issue.

2023-10-19 16:51 UTC, closed without merging