docs: minor cli reference editorial updates
docker/buildx pull request #2117
Opened 2023-11-15 10:51 UTC by dvdksn

Signed-off-by: David Karlsson <35727626+dvdksn@users.noreply.github.com>

2023-11-15 14:36 UTC, crazy-max commented on docs/reference/buildx_version.md
> +github.com/docker/buildx v0.11.0-263-gd537b9e4.m d537b9e418b909b65274a902e25b3d1757553a3b.m
Maybe show a GA release?:

```
github.com/docker/buildx v0.11.2 9872040b6626fb7d87ef7296fd5b832e8cc2ad17
```

2023-11-15 14:40 UTC, crazy-max commented on docs/reference/buildx_imagetools_inspect.md
> -```json
I don't have a really strong preference but I like to highlight JSON output

![image](https://github.com/docker/buildx/assets/1951866/7f2810a9-5045-4efc-bada-f5ef83435390)

2023-11-15 14:47 UTC, crazy-max commented on docs/reference/buildx_create.md
> +* [`remote` driver](https://docs.docker.com/build/drivers/remote/)
I agree that we have these opts in multiple places. We should also make sure docs is being updated when changes are being made. Maybe we should add a comment like in https://github.com/docker/docs/blob/main/content/build/drivers/docker-container.md:

```go
type Driver struct {
	driver.InitConfig
	factory      driver.Factory

    // if you add fields, do not forget to update https://github.com/docker/docs/blob/main/content/build/drivers/docker-container.md
	netMode      string
	image        string
	memory       opts.MemBytes
	memorySwap   opts.MemSwapBytes
	cpuQuota     int64
	cpuPeriod    int64
	cpuShares    int64
	cpusetCpus   string
	cpusetMems   string
	cgroupParent string
	env          []string
}
```

2023-11-16 15:38 UTC, crazy-max requested changes
Some lint issues otherwise LGTM: https://github.com/docker/buildx/actions/runs/6892599910/job/18750273469?pr=2117#step:4:106

```
#13 83.37 driver/kubernetes/driver.go:41: File is not `gofmt`-ed with `-s` (gofmt)
#13 83.37 	factory          driver.Factory
#13 83.37 driver/docker-container/driver.go:43: File is not `gofmt`-ed with `-s` (gofmt)
#13 83.37 	factory      driver.Factory
#13 ERROR: process "/bin/sh -c golangci-lint run" did not complete successfully: exit code: 1
```

2023-11-16 16:38 UTC, crazy-max approved these changes
LGTM

2023-11-16 19:00 UTC, tonistiigi approved these changes

2023-11-16 19:25 UTC, merged