Bake: support compose ssh config
docker/buildx pull request #2445
Opened 2024-05-03 19:36 UTC by sumnerwarren

Adds support for compose ssh config with bake. See [spec](https://github.com/compose-spec/compose-spec/blob/master/build.md#ssh). Based on #1069. This does not remove support for `x-bake` `ssh` field.

2024-05-06 21:25 UTC, tonistiigi approved these changes
fyi @ndeloof

2024-05-08 16:53 UTC, sumnerwarren commented
Looking at the [failed check](https://github.com/docker/buildx/actions/runs/8944019077/job/24651684166?pr=2445): sorting for multiple ssh keys does not appear to be stable. Do we want bake to make it stable or should we just change to an `ElementsMatch` assertion?

2024-05-08 23:47 UTC, tonistiigi commented
@sumnerwarren Is it already coming unsorted from compose? In that case, it should be fixed in there. Meanwhile, we can just add some forced sorting in here to get this merged.

2024-05-09 15:50 UTC, sumnerwarren commented
@tonistiigi Yes, it's coming from compose unsorted, at least on macos. I ran `docker compose config` repeatedly with this MRE compose file to confirm:

```
services:
  test:
    build:
      ssh:
        - default
        - key=key.pem
```

I just pushed a commit that includes sorting.

2024-05-13 10:51 UTC, crazy-max requested changes
Thanks! Don't think we need a separate commit for sorting, can you squash commits please? Otherwise LGTM

2024-05-13 13:50 UTC, crazy-max approved these changes

2024-05-14 08:15 UTC, merged