Fail fast on multi platform build with load
docker/buildx pull request #582
Opened 2021-04-03 10:44 UTC by rumpl

Avoid doing a build if we cannot load the images at the end.

This doesn't really fix anything but at least users will see the error right away and not after a potentially long build.

2021-04-06 20:47 UTC, tonistiigi commented
This should fail fast already without building. Should block it in moby level if not.

For buildx side, this check should be moved to `build/build.go` so that builds from `bake` also pass validation.

2021-04-06 20:48 UTC, tonistiigi commented
hmm 

https://github.com/docker/buildx/blob/84a734dc876a177eca8eb709dc479c3d88220429/build/build.go#L460-L462

2021-04-07 08:10 UTC, rumpl commented
Ok so it's building before failing if the driver is `docker-container`, which has `driver.MultiPlatform: true`

2021-04-07 15:12 UTC, tonistiigi commented
@rumpl Ah, ok. That is different. Add this extra condition to https://github.com/docker/buildx/blob/master/build/build.go#L415

2021-04-22 19:06 UTC, rumpl commented
> ^

👍 I'm moving right now, will get at this next week, sorry

2021-06-24 17:59 UTC, tonistiigi requested changes

2021-06-24 17:59 UTC, tonistiigi commented on build/build.go
> +	if len(opt.Platforms) != 1 && d.Factory().Name() == "docker-container" {
This does not look correct. Multi-platform builds with `docker-container` driver are definitely supported. If I understood your description correctly then the condition you want is to check if exporting is happening to docker. Also, we should never check for driver names. There is a features list for that but don't think you need that atm., just check for the exporter.

2021-06-24 18:03 UTC, rumpl commented
I should check that the exporter is “docker” right?

Sent from mobile - please excuse tone and brevity

> On Jun 24, 2021, at 19:59, Tõnis Tiigi ***@***.***> wrote:
> 
> ﻿
> @tonistiigi requested changes on this pull request.
> 
> In build/build.go:
> 
> > @@ -520,6 +520,10 @@ func toSolveOpt(ctx context.Context, d driver.Driver, multiDriver bool, opt Opti
>  		so.FrontendAttrs["platform"] = strings.Join(pp, ",")
>  	}
>  
> +	if len(opt.Platforms) != 1 && d.Factory().Name() == "docker-container" {
> This does not look correct. Multi-platform builds with docker-container driver are definitely supported. If I understood your description correctly then the condition you want is to check if exporting is happening to docker. Also, we should never check for driver names. There is a features list for that but don't think you need that atm., just check for the exporter.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-24 18:07 UTC, tonistiigi commented
> I should check that the exporter is “docker” right?

Correct

2021-06-25 17:29 UTC, tonistiigi requested changes

2021-06-25 17:29 UTC, tonistiigi commented on build/build.go
> +	if len(opt.Platforms) > 1 && opt.Exports[0].Type == "docker" {
Looks correct but move it to line 458 so all the docker exporter handling is in one place.

2021-06-27 14:51 UTC, crazy-max approved these changes
LGTM

2021-06-28 16:28 UTC, tonistiigi approved these changes

2021-06-28 16:29 UTC, merged